# Generated by Django 5.1.5 on 2025-03-05 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='insurance',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_documents/'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancesubcategory',
            name='description_subcategory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PolicyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Owner',
                'verbose_name_plural': 'Policy Owners',
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='policy_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='insurance.policyowner'),
        ),
    ]
