# Generated by Django 5.1.5 on 2025-03-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_type',
        ),
    ]
